openapi: 3.0.0
info:
  title: TripVair Flight Cancel Predictor API
  description: "Obtain a probability of a future flight being cancelled using deep learning AI."
  version: 1.0.0
tags:
  - name: TripVair Flight Cancel Predictor
paths:
  /flights/v1/cancel:
    get:
      summary: Flight Cancel Predictor
      operationId: fcpcancel
      deprecated: false
      description: ""
      parameters:
        - name: departdate
          in: query
          description: Departs 10/29/2023.
          required: false
          example: 10/29/2023
          schema:
            type: string
        - name: origin
          in: query
          description: Origin city code for departure
          required: false
          example: '"MCO"'
          schema:
            type: string
        - name: dest
          in: query
          description: Destination city code for departure
          required: false
          example: '"JFK"'
          schema:
            type: string
        - name: flightno
          in: query
          description: Flight Number
          required: false
          example: "1140"
          schema:
            type: string
        - name: carrier
          in: query
          description: "Scheduled airline by code "
          required: false
          example: '"AA"'
          schema:
            type: string
        - name: arrivedate
          in: query
          description: "Arrival"
          required: false
          example: 10/29/2023
          schema:
            type: string
        - name: Accept
          in: header
          description: ""
          required: false
          example: application/json
          schema:
            type: string
        - name: Content-Type
          in: header
          description: ""
          required: false
          example: text/csv
          schema:
            type: string
        - name: Keep-Alive
          in: header
          description: ""
          required: false
          example: "120"
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
              x-apidog-ignore-properties: []
              x-apidog-orders: []
      responses:
        "200":
          description: NotLikelyToCancel
          content:
            application/json:
              schema:
                title: '{"statusCode": 200, "isBase64Encoded": false, "cancelLikely":
                  "False", "probability": 0.80483}, message: "Text of results with probability.}"'
                type: object
        "404":
          description: ErrorFlightNumber
          content:
            application/json:
              schema:
                title: '{"statusCode": 404, "isBase64Encoded": false, "message": "error message"}'
                type: object